title: MOLGENIS FusionAuth role manager
email: s.haakma@rug.nl
description: MOLGENIS roles and registration service forn FusionAuth
layout: black #default layout
url: https://molgenis.github.io/molgenis-js-auth

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-target-blank
exclude:
  - adr/**
  - fo/**